CREATE TABLE "pokemon"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "nom" VARCHAR(64) NULL,
  "type" VARCHAR(64) NULL,
  "a1" VARCHAR(64) NULL,
  "a2" VARCHAR(64) NULL
);

CREATE TABLE "type"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "nom" VARCHAR(64) NULL
);

CREATE TABLE "attaque"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "attype" INTEGER NULL,
  "nom" VARCHAR(64) NULL,
  "id_type" VARCHAR(64) NULL
);

CREATE TABLE "inventaire"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "nom" VARCHAR(64) NULL,
  "type" INTEGER NULL,
  "a1" INTEGER NULL,
  "a2" INTEGER NULL
);

CREATE TABLE "meilleurs"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "nom" VARCHAR(64) NULL,
  "prim1" VARCHAR(64) NULL,
  "prim2" VARCHAR(64) NULL,
  "cha1" VARCHAR(64) NULL,
  "cha2" VARCHAR(64) NULL,
  "cha3" VARCHAR(64) NULL
);
